url: https://tkhomep.github.io
collections:
  products:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "default"
  - 
    scope:
      path: ""
      type: categories
    values:
      layout: category